### Live Bids
GET https://freighteg.in/freightapi/liveBids?company_id=665580f353ccced94082681b
Accept: application/json

###

### Get Bid Results
GET https://freighteg.in/freightapi/getBidResults?company_id=665580f353ccced94082681b
Accept: application/json

###

### Get Bid Result History
GET https://freighteg.in/freightapi/getBidResultHistory?company_id=665580f353ccced94082681b
Accept: application/json

###

### Counters
GET https://freighteg.in/freightapi/counters?company_id=665580f353ccced94082681b
Accept: application/json

###

### Canceled Request (You may need to complete the URL)
GET https://freighteg.in/freightapi/can
Accept: application/json

###
### Cancelled Bids Request
GET https://freighteg.in/freightapi/cancelledBids?company_id=665580f353ccced94082681b


### Create Branch API
POST https://freighteg.in/freightapi/addBranch
Content-Type: application/json

{
  "name": "{{name}}",
  "contact_person_name": "{{contactname}}",
  "phone": "{{number}}",
  "role": "branch",
  "password": "{{password}}",
  "company_id": "{{userData?.id}}"
}

### Update Branch API
PUT https://freighteg.in/freightapi/updatebranches/{{branchData._id}}
Content-Type: application/json

{
  "name": "{{name}}",
  "contact_person_name": "{{contactName}}",
  "phone": "{{number}}",
  {{#if newpassword && newpassword.trim() !== ""}}
  "password": "{{newpassword}}"
  {{/if}}
}

### Get Branch Data by Branch ID
GET https://freighteg.in/freightapi/getbranchdetails/66b3cb50c07c66605d6909c4

### Get All Branches by Company ID
GET https://freighteg.in/freightapi/getbranches/company/665580f353ccced94082681b


### Login to Freight API
POST https://freighteg.in/freightapi/freightuser/login
Content-Type: application/json

{
    "role": "Staff",
    "phone": "1234567890",
    "password": "123456"
}
