# Get wallet info by company id
GET https://freighteg.in/freightapi/freightWalletBalance/665580f353ccced94082681b

###

# Fetch FASTAG paid by company id
POST https://freighteg.in/freightapi/ULLIPtracking
Content-Type: application/json

{
  "company_id": "665580f353ccced94082681b",
  "tracking_For": "FASTAG",
  "parameters": {
    "vehiclenumber": "HR55AQ5994"
  }
}

###

# Fetch SARATHI by company id
POST https://freighteg.in/freightapi/ULLIPtracking
Content-Type: application/json

{
  "company_id": "12345",
  "tracking_For": "SARATHI",
  "parameters": {
    "dlnumber": "DL123456789",
    "dob": "1990-01-01"
  }
}

###

# Fetch VAHAN by company id
POST https://freighteg.in/freightapi/ULLIPtracking
Content-Type: application/json

{
  "company_id": "12345",
  "tracking_For": "VAHAN",
  "parameters": {
    "vehiclenumber": "AB1234CD"
  }
}

###
# Get Payment History by User ID
GET https://freighteg.in/freightapi/paymentHistory/665580f353ccced94082681b
# Authorization: Bearer your_dummy_access_token

###

# Get Companies by User ID
GET https://freighteg.in/freightapi/get-companies/665580f353ccced94082681b
# Authorization: Bearer your_dummy_access_token

###

# Get Freight Wallet Balance by Company ID
GET https://freighteg.in/freightapi/freightWalletBalance/665580f353ccced94082681b
# Authorization: Bearer your_dummy_access_token

###

POST https://freighteg.in/freightapi/freightuser/login
Content-Type: application/json

{
    "role": "vendor",
    "phone": "1234567890",
    "password": "123456"
}

###
GET https://freighteg.in/freightapi/rank-by-vendor/668d168060d1af2a06fa2ab4
Content-Type: application/json

####
GET https://freighteg.in/freightapi/get-companies/665580f353ccced94082681b


###
POST https://freighteg.in/freightapi/freightuser
Content-Type: application/json
{
    "name": "hfihi",
    "phone": "1234567899",
    "role": "Field staff",
    "password": "12345",
    "company_id": "665580f353ccced94082681b",
    "branch_id":"66c03d9a7d7b083d83c04e10"
}
###
GET https://freighteg.in/freightapi/pod/pending/668d168060d1af2a06fa2ab4


###
GET https://freighteg.in/freightapi/pod/history/66c03d9a7d7b083d83c04e10


###
GET https://freighteg.in/freightapi/pod/history/66c03d9a7d7b083d83c04e10